[package]
name = "pkg"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
futures-util = "0.3.30"
indicatif = "0.17"
reqwest = { version = "0.11.23", features = ["stream"] }
serde = { version = "1.0.194", features = ["derive"] }
shellexpand = "3"
sqlx = { version = "0.7", features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1", features = ["full"] }
toml = "0.8"
